# Site settings
baseurl = "https://openarmsministry.org/"
# baseurl = "http://b48cd5d2.ngrok.io/"
languageCode = "en-us"
title = "Open Arms Ministry"
theme = "hugo-highlights-theme"

# Enter your tracking code to enable Google analytics
googleAnalytics = "UA-82352339-1"

[params]

  # You can use Markdown for urls [text](//domain.tld/source)
  #
  # All icons using Fontawesom's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons.

  # To provide more meta data for search engings feel free to add a few informations.
  # This lines will be inserted as meta tags.
  name = "Open Arms Ministry Chicago"
  description = ""

  # For a static site it's not possible to provide a contact form. The contact form uses
  # www.formspree.io as a proxy. The form makes a Post request to their servers to send an email
  # Visitors can send up to a 1000 emails each month
  #
  # How to setup formspree
  #
  # - set your email address under 'email' below
  # - upload the generated site to your server
  # - send a dummy email to yourself to confirm your account
  # - click the confirmation link in the email from www.formspree.io
  # - That's all. Enjoy mailing!
  email = "feedback@openarmsministry.org"
  
    # Hero Section
  [params.hero]
    logo = "logo.png"
    title = "Open Arms Ministry"
    description = "Share. Connect. Provide."
    buttonText = "Learn more"

    # Call to Action
  [params.cta]
    enable = true
    title = "Drive for Five"
    description = "In honor of Homelessness Awareness Month, Open Arms Ministry is launching its first Drive For Five Campaign!<br><br>We’re raising the bar and looking for one-hundred partners willing to help us reach our goal of $5000 by making a donation of at least $50, during the month of November! <h3>Will you be one?</h3> <p>Your generous donation will help us cover the start-up expenses of our New Open Arms Apparel, launched to create a path for our organization, and the people we serve, to become more self-sufficient by:</p><ul><li>Creating job opportunities in Design, Operations, and Sales &amp; Marketing for our brothers and sisters in need</li><li>Expanding our days of operation</li><li>Improving our ability to address the issues of homelessness and hunger holistically by increasing the program offerings at our Drop-In</li><li>Providing a modest stipend to our brothers and sisters, currently experiencing financial poverty, yet still freely give of themselves to ensure others in need are able to receive a warm meal, when they visit Open Arms Ministry</li></ul><h4>Special Offer</h4><ul><li>$100 Donors will receive an Official Open Arms Ministry hoodie</li><li>$150 Donors will receive an Official Open Arms hoodie &amp; one hoodie will be! donate to someone in need, on your behalf!</li></ul><h3>TOGETHER, WE WILL REACH OUR GOAL!</h3><br><br>Support A  Beloved Community Of Individuals, United To Transform Our City And Fight Against Poverty, Hunger, and Homelessness<br><br>Shop Today &amp; Check Back Often For Our Newest Items!"
    buttonText = "Join the 100!"
    buttonLink = "https://secure.lglforms.com/form_engine/s/1-WiPfjS1CTLHROy0oDIgw"

  # infos section
  [params.infos]
    enable = true
    title = "Official Open Arms Apparel"
    description = "When you wear Open Arms Apparel, not only will you LOOK GOOD, you will help further our mission to provide increased access to: <ul><li>Employment Opportunities</li><li>Physical &amp; Mental Healthcare</li><li>Warm Meals &amp; Clean Clothes</li><li>Quality Housing</li><li>Other Needed Resources</li></ul>"
    buttonText = "Online Shop"
    buttonLink = "https://www.storefrontier.com/store/open-arms-ministry"
    # the picture is storead at static/images/
    # picture = "pic03.jpg"

    # about section
  [params.about]
    enable = true
    title = "Who We Are"
    description = "Open Arms Ministry supports and partners with those struggling with homelessness, poverty, and food insecurity to enhance human dignity, community, and opportunity.<br><br>We strive to develop a safe community through providing basic needs and the opportunity to build individual and community capacity. Within this vision is this assumption that in order to best serve OAM participants, looking at and responding to the root causes of both food insecurity and homelessness is needed."
    buttonText = "next"
    # the picture is storead at static/images/
    # picture = "wall-panhandling.jpg"

  # skill section
  [params.skill_list]
    enable = true
    title = "What we do"
    description = "Open Arms Ministry provides access to programs and service that help meet some of the basic needs of those who are currently experiencing the effects of financial poverty, namely homelessness and hunger.  We believe in everyone’s ability to achieve a life of joy, fulfillment, and financial stability. However, the basic needs of food, shelter, clothing, and safety must be met for a person to begin setting other goals in their lives.  We seek to work with our brothers and sisters who are in a state of financial Dependence and journey with them along a path that moves to Independence. Our first step is to expand the programming in a way that provides us the opportunity to meet basic needs in a holistic way.<br><br>Currently, Open Arms has two programs operating on the Northwest side of Chicago:"
    buttonText = "next"
    # the picture is storead at static/images/
    # picture = "pic02.jpg"

    [[params.skills]]
      icon = "fa-child"
      title = "Drop-In"
      description = "We gather as a family to share meals and provide access to basic needed resources. Clean clothing &amp; toiletries, identification cards and healthcare are just a few. We also collectively work to conceive, develop, and implement further programming that will allow us to control our future!  ALL ARE WELCOME!"
    
    [[params.skills]]
      icon = "fa-cutlery"
      title = "Food Pantry"
      description = "Working in conjunction with the Greater Chicago Food Depository, we serve ANY families and individuals who live in the area bounded by Irving Park, Fullerton, Pulaski, and Western."

    [[params.skills]]
      title = "Why we do it"
      description = "Because in the richest country in the world, NO ONE SHOULD BE HOMELESS OR HUNGRY! We are bonded together for a common purpose: to UNIFY, to BUILD COMMUNITY, and to TAKE CARE of the people in it!"

  [params.program]
    enable = true
    title = "Program Hours/Info"
    description = "<h4>Location</h4> 2649 N Francisco Ave. <br> Chicago, IL 60647 <br><br> <h4> Drop-In </h4> Every Tuesday, Wednesday and Thursday <br> 10am-2pm <br> <a href='mailto:dropin@openarmsministry.org'>dropin@openarmsministry.org</a> <br>  <br> <h4>Food Pantry</h4> Every Wednesday <br> 4pm-6pm <br> <a href='mailto:pantry@openarmsministry.org'>pantry@openarmsministry.org</a><br><br><h4>Community Dinner</h4> Every 2nd Thursday of the month (Except December) <br> 5:30PM-7PM <br> We gather to build and strengthen the bonds of community between Open Arms, the people we serve, Logan Square, and other Chicagoland neighborhoods over a delicious meal."
  
  [params.volunteer]
    enable = true
    title = "GET INVOLVED"
    description = "<ul><li>Committed, regular volunteers are needed in order for the Drop-In, Food Pantry, &amp; Community Dinners to function effectively.</li><li>Volunteers are also needed to help us build our capacity.  We are always looking for volunteers to assist us with Relationship/Partnership Development, Financial Oversight, Strategic Planning, Volunteer Management, Fundraising, and Marketing/Communications</li><li>We believe all of natural gifts can be mobilized to positively impact ourselves and others. So if you have particular skills, talents, or passions that you can share, we’d love to have your help in the quest to achieve our mission.</li></ul><p>We would love for you to join our family! Fill out the volunteer application, and we will be in touch soon!</p>"
    buttonText = "Volunteer"
    buttonLink = "http://bit.ly/oamvolunteer"

  [params.donate]
  enable = true
  title = "Donate"
  description = "Your financial donations will contribute to our ability to further the Open Arms mission of enhancing human dignity and providing food and essential services for people in Chicago. <br> <br> Open Arms Ministry is a 501&#40;c&#41;3 non-profit organization; donations are tax-deductible."
  buttonLink= "https://donate.openarmsministry.org"
  buttonText= "Donate"

  # footer section
  # this section includes
  #
  # - the contact form
  # - social icons
  #
  # It's possible to disable the whole footer or disable only social icons or contact form
  [params.subscribe]
    enable = true
    title = "Subscribe to our Newsletter"
    description = "We are excited to share with you what we are working on.  If you are interested, please follow the link below and subscribe to our newsletter."
    buttonText = "Subscribe"
    link = "http://eepurl.com/cjtmJv"
    
  [params.footer]
    enable = true
    title = "Get in Touch"

    # contact form
    [params.footer.contact]
      enable = true

    [params.footer.contact.form]
      name = "Name"
      email = "Your Email"
      message = "Your Message"
      buttonText = "send message"

    # social icons
    [params.footer.social_list]
      enable = true
      [[params.footer.social]]
        title = "Twitter"
        icon = "fa-twitter"
        link = "https://twitter.com/@openarmschicago"
      
      [[params.footer.social]]
        title = "Linkedin"
        icon = "fa-linkedin"
        link = "https://www.linkedin.com/company/open-arms-ministry"

      [[params.footer.social]]
        title = "Instagram"
        icon = "fa-instagram"
        link = "https://www.instagram.com/openarmsmin/"

      [[params.footer.social]]
        title = "Facebook"
        icon = "fa-facebook"
        link = "https://www.facebook.com/openarmschicago"

    # copyright
    #[params.footer.copyright.notice]

      [[params.footer.copyright.notice]]
        text = "© Open Arms Ministry"
